### ISSUE TITLE
Index out of range exception in function `hexStringToByteArray`

### ISSUE THREAD

**Issue by ecruzolivera** [bastengao/react-native-usb-serialport-for-android#19]
Hello, every time that i send a string via the [send](https://github.com/bastengao/react-native-usb-serialport-for-android/blob/50d9c34091af5197209a6c809108d63e90ec857c/src/usb_serial.tsx#L37) function, im getting this exception:
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 1
    at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
    at java.base/java.lang.String.charAt(String.java:1515)
    at Main.hexStringToByteArray(Main.java:11)
    at Main.main(Main.java:18)
 ```

Im able to repro the issue without using React Native, just a plain hello world level Java example:

``` java
public class Main {
  public static byte[] hexStringToByteArray(String s) {
      int len = s.length();
      byte[] data = new byte[len / 2];
      for (int i = 0; i < len; i += 2) {
          data[i / 2] = (byte) ((Character.digit(s.charAt(i), 16) << 4)
              + Character.digit(s.charAt(i + 1), 16));
      }
      return data;
  }
  
  public static void main(String[] args) {
    String hex = "1";
    byte[] result = hexStringToByteArray(hex);
    System.out.println(result);
  }
}
```

**Comment by VMBindraban** [comment]
We are having the same issue. Logcat is returning the following:

```
11-11 14:32:08.946 29879 29918 E ReactNativeJS: Could not send command to display: Error: Exception in HostFunction: length=27; index=27
11-11 14:32:08.959 29879 29919 E unknown:ReactNative: console.error: Could not send command to display: Error: Exception in HostFunction: length=27; index=27, stack:
```
